name: release

on:
  push:
    branches: master # master 分支提交时触发

jobs:
    release-job：
      runs-on: ubuntu-20.04
      steps: # 步骤
        - uses: actions/checkout@master # 使用公共的 action
        - uses: actions/setup-node@v4.0.2
          with: 
            node-version: '20.11.1'
        - run: echo '发布'
  
